# Generated by Django 5.1.1 on 2024-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_custom_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], max_length=100, null=True),
        ),
    ]
