# Generated by Django 5.1.1 on 2024-09-26 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_custom_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='usertype',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('admin', 'Admin')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=100, null=True)),
                ('proifle_pic', models.ImageField(null=True, upload_to='Media/proifle_pic')),
                ('carrer_summary', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
