# Generated by Django 5.1.1 on 2024-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_custom_user_usertype_basicinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], max_length=100, null=True),
        ),
    ]
