# Generated by Django 5.1.1 on 2024-09-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_custom_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full_time'), ('part_time', 'Part_time')], max_length=50, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='usertype',
            field=models.CharField(choices=[('jobseeker', 'jobseeker'), ('recruiter', 'Recruiter')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BasicInfoModel',
        ),
    ]
