# Generated by Django 5.1.1 on 2024-09-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_jobmodel_user_alter_jobmodel_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='usertype',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('recruiter', 'Recruiter')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='jobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, max_length=200, null=True, upload_to='media/resume')),
                ('cover', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.jobmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
